repository_type: pipeline

nf_core_version: 3.2.0

lint: {}

template:
  org: nf-core
  name: snippet
  description: short-read Non-Invasive Prenatal pipeline examination Tool
  author: Rasmus Burge, Ramprasad Neethiraj, Jesper Eisfeldt
  version: 1.0.0dev
  force: true
  outdir: .
  skip_features: []
  is_nfcore: true
